//test exception 6
//test abort


int f( int a) {
  return a + 1;
}


int main() {
  int x = 100;

  for( int i = 0; i < x; i = f(i) ){
    assert(x - 1 > i);
  }

  return x;
}
